### ISSUE TITLE
No catkin-sphinx package

### ISSUE THREAD

**Issue by progtologist** [ros-infrastructure/catkin-sphinx#6]
There appears to be an inconsistency with catkin-sphinx. In the [catkin docs](http://docs.ros.org/indigo/api/catkin/html/index.html) it says that you are able to install this with synaptic, although this is not actually the case. Perhaps the documentation should be updated to match the correct way of documenting using sphinx.

**Comment by jack-oquin** [comment]
And, what is the correct way of documenting using this package?

Specifically, how is it installed?

**Comment by tfoote** [comment]
Looking at the new buildfarm we mostly use it from source: https://github.com/ros-infrastructure/ros_buildfarm/search?utf8=%E2%9C%93&q=catkin-sphinx which allows us to fix things quickly. It is available on pip, which we appear to use in the distro independent doc jobs. 

We can definitely update the docs: http://docs.ros.org/indigo/api/catkin/html/adv_user_guide/builddocs.html?highlight=sphinx to not mention pulling from apt.

I"m not sure the best way to document using this package. It's basically just the recommended theme used when running sphinx with ros. It's not really directly connected to catkin, and could be considered to be collapsed into rosdoc_lite since it's the default theme: https://github.com/ros-infrastructure/rosdoc_lite/blob/a178342e434c9147f7c21dcffdd93a245e6fca44/doc/conf.py#L108 though it requires custom code in conf.py https://github.com/ros-infrastructure/rosdoc_lite/blob/a178342e434c9147f7c21dcffdd93a245e6fca44/doc/conf.py#L19-L20

The theme is currently possible to be used separately, but the overhead seems high.

**Comment by jack-oquin** [comment]
The problem I'm seeing right now is when running ``rosdoc_lite`` on a local development machine. Ideally, that generate the same output as the build farm.

But, today I discovered that ``rosdoc_lite`` can't even document *itself*, due to the lack of this package.

I am sure I can figure out a way to check it out into my workspace, but it's not even a catkin package, so I guess I'd have to use ``catkin_make_isolated``, or something. Meanwhile that would not help anyone else with similar problems.

Including it in ``rosdoc_lite`` would presumably fix that, and perhaps makes sense. I don't know, because I don't fully understand what it's doing. What are the problems with doing that?

**Comment by tfoote** [comment]
> I am sure I can figure out a way to check it out into my workspace, but it's not even a catkin package, so I guess I'd have to use catkin_make_isolated, or something. Meanwhile that would not help anyone else with similar problems.

It's just a plain python package that needs to be on you PYTHON_PATH it's generally recommended to simply install it onto your system.  (The apt or pip installs will go into /usr)

Folding it into rosdoc_lite will break anyone relying on it standalone. It has been packaged as an RPM https://www.rpmfind.net/linux/rpm2html/search.php?query=python-catkin-sphinx but it was specifically packaged to support the packaging of ROS package. If people want to keep using it we can leave the sources and package on pypi and recommend that they fork it for future use. But I don't know of anyone using it externally. And the pypi download counts don't look like there's significant usage outside of our buildfarm. And we haven't packaged any new debs since somewhere near the last release in 2012. And there have been only 1 or 2 commits since then too.

**Comment by jack-oquin** [comment]
So, we just need to update the docs to recommend ``pip``? 

Is there actually a Debian package? I can't find one, what's its name?

**Comment by tfoote** [comment]
We could just recommend pip, or merge them together.

Yes, the debs are only on the much older platforms such as lucid: http://packages.ros.org/ros/ubuntu/dists/lucid/main/binary-amd64/Packages

**Comment by jack-oquin** [comment]
The Debian package was a good solution. It could be referenced with a ``<doc_depend>``. I wonder why it was dropped, too much effort?

@tfoote: I don't much care how this gets resolved. What do you want to do?

**Comment by tfoote** [comment]
I don't think that the functionality has much general purpose reusability, and as far as I can tell it's not being used outside of rosdoc_lite. As such I'd suggest avoiding the overhead of the extra package to releases and maintain and just fold the content into rosdoc_lite. 

The main content is the cmake sphinx domain which looks like it might be available upstream: https://cmake.org/cmake/help/v3.0/manual/cmake-developer.7.html#cmake-domain we could leave it as is. Otherwise it's just the ros-theme for sphinx which is just selecting some pygments settings.

**Comment by dirk-thomas** [comment]
Doing a release takes literally less then one minute. And if the update rate stays the same as in the past there won't we no work in the future for this.

Folding this into `rosdoc_lite` on the other hand will need changes for all platforms which have packages this: arch, rpm, etc.

From my point of view folding is disrupting others while just doing one release is almost free. Therefore I don't agree with the conclusion to go for the folding.

**Comment by tfoote** [comment]
> Doing a release takes literally less then one minute. And if the update rate stays the same as in the past there won't be any work in the future for this.

Indeed, doing a release is relatively quick. But it's just one more package on the list of packages we need to monitor and it will need to be periodically ported forward and potentially rereleased for each new supported platform. As can be seen it's already been neglected due to it not being actively used even by us. 

> Folding this into rosdoc_lite on the other hand will need changes for all platforms which have packaged this: arch, rpm, etc.

Can you explain what changes you're talking about? As far as I can see this won't require any changes on the other platforms, it will just be integrated into `rosdoc_lite` and you won't need to worry about the old package. And if we drop support for releasing this package we will remove the burden on any of the packaging needs for the other platforms in the future too, since they won't need to package it anymore either.

Looking a little deeper, we use the catkin_sphinx for the theme only in 

> From my point of view folding is disrupting others while just doing one release is almost free. Therefore I don't agree with the conclusion to go for the folding.

Dropping this dependency will not effect any others who are using it. They can continue using any of the released versions that they want. And if they want to fork and maintain/improve it in the future that's fine. We just don't need to keep support for releasing this going forward.

Removing the dependency will simplify documentation instructions (which this thread is about). It will also simplify the process of running the doc jobs and decrease their overhead. (One less thing to clone etc)

It's been 3 years since we've released it and no one has complained. I think that's a relatively good indication that it's not used. As little overhead as making a release may be, it's still overhead that I think should be cut. 





Auditing I found there were only 3 doc independent packages using it via pip. rospkg rosdep and jenkins_tools only for the theme. 

I've opened PRs to clear them all: 
rospkg https://github.com/ros-infrastructure/rospkg/pull/98
rosdep https://github.com/ros-infrastructure/rosdep/pull/446

jenkins_tools is EOL so I just proposed to remove it from the farm: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/37 and https://github.com/ros-infrastructure/ros_buildfarm_config/pull/36

Commented in jenkins_tools as well: https://github.com/ros-infrastructure/jenkins_tools/pull/26
And commented as such in the jenkins_scripts readme too: https://github.com/ros-infrastructure/jenkins_scripts/pull/79

**Comment by wjwwood** [comment]
So we're going to copy the contents of this (or go back to the default sphinx theme) into `rospkg`, `rosdep`, and `rosdoc_lite`?

Is that really better than releasing it? I'm also very dubious of this conclusion. Duplicating the theme to multiple places (especially since it's already consolidated) is a really bad software engineering smell to me. I can just imagine a PR against `rospkg` to fix the theme's CSS and it never getting propagated to the other places.

I'm sorry, but I also don't agree with the conclusion that we should stop hosting the theme separately. From my perspective, it's not to encourage reuse outside of our group, but simply a sane way to distribution this common resource amongst our packages. This is a common practice in Sphinx, for example RTD's theme is distributed in this way: https://github.com/snide/sphinx_rtd_theme

**Comment by wjwwood** [comment]
If the question is effort, I'll gladly take on releasing this package and keeping it up-to-date rather than see code duplicated across repositories unnecessarily.

**Comment by wjwwood** [comment]
Is there a build farm job failing or something that prompted this action (or the action to switch to the default theme in `rospkg` and `rosdep`)?

"Where's the fire?"

**Comment by jack-oquin** [comment]
The only problem I'm seeing is the minor annoyance that I can't run ``rosdoc_lite`` on itself as a development test. 

Plus, I dislike having this as an undeclared dependency. Isn't that the kind of thing ``<doc_depend>`` was supposed to handle?

Whatever you guys agree on is fine with me. I only maintain ``rosdoc_lite`` to help out, anyway.

**Comment by wjwwood** [comment]
@jack-oquin what, in your estimation, is the issue that prevents you from running `rosdoc_lite` on itself. How does it interact with `catkin-sphinx`?

You said before:

> But, today I discovered that rosdoc_lite can't even document itself, due to the lack of this package.

Does that mean the doc job fails or you need to install the `catkin-sphinx` package before you can build the docs locally?

**Comment by jack-oquin** [comment]
``rosdoc_lite`` depends on ``catkin-sphinx``, although that dependency is undocumented. 

I have to install ``catkin-sphinx`` in order to run ``rosdoc_lite`` on itself. The documentation for how to do that is broken: it says to run ``apt-get``, which does not work.

I discovered this while trying to fix an new (and unrelated) build farm failure for ``rosdoc_lite``. The build farm how considers it a failure when the ``_static`` HTML is non-existent. It never complained about that warning before.

**Comment by dirk-thomas** [comment]
@jack-oquin Can you please post a link to a job which failed because of that.

**Comment by jack-oquin** [comment]
> Can you please post a link to a job which failed because of that.

No. 

I say again: the failure happens when building the docs locally. I only needed to do that because something else was failing on the build farm.

**Comment by jack-oquin** [comment]
@dirk-thomas: maybe I misunderstood your question. If you wanted a link to the _static HTML problem, here was the last failure before I fixed it:

* http://build.ros.org/view/Jdoc/job/Jdoc__rosdoc_lite__ubuntu_trusty_amd64/8/

**Comment by dirk-thomas** [comment]
The referenced job has not failed but is marked unstable. The old build farm did not care about warnings. But the new build farm marks a doc job as unstable when certain warnings are detected because often warnings are indicating a problem.

**Comment by jack-oquin** [comment]
Whatever you choose to call it, that is the problem I was fixing.

**Comment by wjwwood** [comment]
Well, I merged a pr and fixed some stuff up and made a new release `0.2.2`. I also ran the release process so now you should be able to install from apt-get and pip for our currently supported platforms. The linked to catkin docs (https://github.com/ros-infrastructure/catkin-sphinx/issues/6#issue-87061254) should work now, and @jack-oquin you should be able to have a `<doc_depend>` on it for now.

Separately, if we want to move away from this packages by merging the theme into `rosdoc_lite` (and subsequently dropping the `<doc_depend>`, changing to the default theme in `rospkg` and `rosdep`, move to the upstream cmake Sphinx domain, and update the linked to catkin docs, then we can continue to do that. If we do those things we can safely neglect to add apt-get packages for this in newer Ubuntu releases.

**Comment by jack-oquin** [comment]
Thanks, @wjwwood.

With that package installed manually, ``rosdoc_lite`` can now document itself. Those docs aren't very good, but that's a separate problem. :smile: 

Before I can add a ``<doc_depend>``, I'll need a ``rosdep`` key. By analogy to ``python-catkin-tools``, I suppose it should look something like this:
```
python-catkin-sphinx:
  fedora: [python-catkin_sphinx]
  osx:
    pip:
      packages: [catkin_sphinx]
  ubuntu: [python-catkin-sphinx]
```
Will there be a Fedora release, too? Are there other systems we need to support? 

I don't want to release ``rosdoc_lite`` without covering all the relevant platforms.

**Comment by wjwwood** [comment]
That should be fine as the entry. Normally the fedora crew make the fedora packages. I think it might be prudent to make our decision about whether to move away from this package or not before involving the fedora community. If they want to package it up in the meantime that's fine but if we're going to move away from it, then it might be a waste for them to package it up. My intention by releasing this again was to address the problem in the short term.

**Comment by jack-oquin** [comment]
Sounds like it's up to them, then. I'll wait until I hear about that before updating any rosdep files.

@cottsay?

**Comment by cottsay** [comment]
Fedora has had a `catkin-sphinx` packaged for quite some time. However, this package breaks pattern a little bit and is named like the Ubuntu package, `python-catkin-sphinx`.

Thanks for asking, @jack-oquin!

**Comment by cottsay** [comment]
I'm updating the Fedora package to `0.2.2` now.

Side note - thanks for tagging the release in the repo, @wjwwood. It makes packaging a bit easier.

--scott

**Comment by jack-oquin** [comment]
I'll make a rosdep update using ``python-catkin-sphinx`` for fedora. I hope that will cover all the relevant platforms.
